swagger: "2.0"
info:
  title: PyWebExec API
  version: "1.0"
paths:
  /commands:            # changed from /run_command
    get:
      summary: "List commands status"
      responses:
        "200":
          description: "List of all commands status"
    post:
      summary: "Run a command"
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: commandRequest
          schema:
            type: object
            properties:
              command:
                type: string
              params:
                type: array
                items:
                  type: string
              rows:
                type: integer
              cols:
                type: integer
      responses:
        "200":
          description: "Command started"
  /commands/{command_id}:
    get:
      summary: "Get command status"
      parameters:
        - in: path
          name: command_id
          required: true
          type: string
      responses:
        "200":
          description: "Command status returned"
  /executables:
    get:
      summary: "List executables"
      responses:
        "200":
          description: "List of executables returned as an array of executable names"
